version: "3"
services:
  web:
    environment:
      - DB_URL=mongodb://maitredb_db_1
    build: .
    volumes:
     - .:/app
     - /data/db
  db:
    image: 'mongo'
    volumes:
     - /data/db
    ports:
      - 27017:27017
